# Generated by Django 4.1.1 on 2022-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='count',
            new_name='count_adult',
        ),
        migrations.AddField(
            model_name='booking',
            name='count_child',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
