# Generated by Django 4.1.1 on 2022-10-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rides',
        ),
    ]
