# Generated by Django 4.1.2 on 2022-11-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile',
        ),
    ]
