# Generated by Django 4.1.1 on 2022-11-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0002_rename_count_booking_count_adult_booking_count_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='count_adult',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='count_child',
            field=models.FloatField(default=1),
        ),
    ]
