# Generated by Django 4.1.1 on 2022-11-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0003_alter_booking_count_adult_alter_booking_count_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package1',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='package2',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
