# Generated by Django 4.1.1 on 2022-11-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0003_rename_image_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='image',
        ),
    ]
