# Generated by Django 4.1.1 on 2023-03-01 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0004_remove_payments_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_login',
            fields=[
                ('user', models.EmailField(default=1, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('type', models.BooleanField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='food_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amuseapp.food_login')),
            ],
        ),
    ]
