# Generated by Django 4.1.1 on 2022-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0004_alter_package1_price_alter_package2_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='count_adult',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='count_child',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package1',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package2',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
