# Generated by Django 4.1.1 on 2022-11-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0005_alter_booking_count_adult_alter_booking_count_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='count_adult',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='count_child',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package1',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package2',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
