# Generated by Django 4.1.1 on 2022-11-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0006_alter_booking_count_adult_alter_booking_count_child_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='package2',
            new_name='Adultpackage',
        ),
        migrations.RenameModel(
            old_name='package1',
            new_name='Childpackage',
        ),
        migrations.RenameField(
            model_name='adultpackage',
            old_name='p2_id',
            new_name='p1_id',
        ),
        migrations.RenameField(
            model_name='childpackage',
            old_name='p1_id',
            new_name='p2_id',
        ),
    ]
