# Generated by Django 4.1.1 on 2022-11-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0008_alter_booking_p1_id_alter_booking_p2_id_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='count_child',
            field=models.BigIntegerField(default=1, null=True),
        ),
    ]
