# Generated by Django 4.1.1 on 2022-11-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0010_remove_rides_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
            ],
        ),
    ]
