# Generated by Django 4.1.2 on 2023-02-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amuseapp', '0003_initial'),
        ('amuseapp', '0011_amount'),
    ]

    operations = [
    ]
